exclude = '''
/(
    \.git
  | \.idea
  | \.hypothesis
  | \.idea
  | \.pytest_cache
  | dist
  | public
)/
'''

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"